### ISSUE TITLE
TypeError: linspace() got an unexpected keyword argument 'dtype'

### ISSUE THREAD

**Issue by somakray** [uweschmitt/pyprophet#22]
Hi I'm trying to run pyprophet and getting the following error. The data set contains fewer decoys(10). 

```
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,541: config settings:
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,542:     apply_scorer: None
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,542:     apply_weights: None
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,542:     compute.probabilities: False
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,542:     d_score.cutoff: -1000.0
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,542:     delim.in: 	
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,542:     delim.out: 	
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,542:     export.mayu: False
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,542:     final_statistics.emp_p: False
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,542:     final_statistics.fdr_all_pg: False
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,543:     final_statistics.lambda: 0.4
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,543:     ignore.invalid_score_columns: 1
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,543:     input_file: True
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,543:     is_test: 0
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,543:     multiple_files.merge_results: 0
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,543:     num_processes: 1
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,543:     out_of_core: 0
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,543:     out_of_core.sampling_rate: 0.1
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,543:     random_seed: None
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,543:     semi_supervised_learner.initial_fdr: 0.15
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,544:     semi_supervised_learner.initial_lambda: 0.4
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,544:     semi_supervised_learner.iteration_fdr: 0.02
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,544:     semi_supervised_learner.iteration_lambda: 0.4
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,544:     semi_supervised_learner.num_iter: 5
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,544:     semi_supervised_learner.stat_best: 0
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,544:     semi_supervised_learner.use_best: 0
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,544:     target.compress_results: 0
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,544:     target.dir: None
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,544:     target.overwrite: 0
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,544:     target.prefix: None
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,545:     xeval.fraction: 0.5
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,545:     xeval.num_iter: 5
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,564: process 15ug_UF_DIA_NoPTRC_160309233604.mzXML.CombinedResults.tsv
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,653: learn and apply classifier from input data
WARNING  -- [pid= 2565] : 2016-03-10 17:00:53,660: %s. pyprophet skips this.
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,699: data set contains 10 decoy and 170 target transition groups
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,703: summary input file:
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,703:    3518 lines
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,704:    180 transition groups
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,704:    27 scores including main score
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,704: learn and apply scorer
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,704: start 5 cross evals using 1 processes
INFO     -- [pid= 2565] : 2016-03-10 17:00:53,704: start learn_randomized
INFO     -- [pid= 2565] : 2016-03-10 17:00:54,321: end learn_randomized
INFO     -- [pid= 2565] : 2016-03-10 17:00:54,321: start learn_randomized
INFO     -- [pid= 2565] : 2016-03-10 17:00:54,778: end learn_randomized
INFO     -- [pid= 2565] : 2016-03-10 17:00:54,778: start learn_randomized
INFO     -- [pid= 2565] : 2016-03-10 17:00:55,228: end learn_randomized
INFO     -- [pid= 2565] : 2016-03-10 17:00:55,229: start learn_randomized
INFO     -- [pid= 2565] : 2016-03-10 17:00:55,670: end learn_randomized
INFO     -- [pid= 2565] : 2016-03-10 17:00:55,670: start learn_randomized
INFO     -- [pid= 2565] : 2016-03-10 17:00:56,115: end learn_randomized
INFO     -- [pid= 2565] : 2016-03-10 17:00:56,116: finished cross evals
INFO     -- [pid= 2565] : 2016-03-10 17:00:56,116: 
WARNING  -- [pid= 2565] : 2016-03-10 17:00:56,141: %s. pyprophet skips this.
INFO     -- [pid= 2565] : 2016-03-10 17:00:56,151: data set contains 10 decoy and 170 target transition groups
INFO     -- [pid= 2565] : 2016-03-10 17:00:56,158: mean m_score = 2.474752e-03, std_dev m_score = 1.411551e-03
INFO     -- [pid= 2565] : 2016-03-10 17:00:56,158: mean s_value = 8.696018e-01, std_dev s_value = 2.020518e-01
Traceback (most recent call last):
  File "/usr/local/bin/pyprophet", line 9, in <module>
    load_entry_point('pyprophet==0.20.1', 'console_scripts', 'pyprophet')()
  File "/usr/local/lib/python2.7/dist-packages/pyprophet/main.py", line 364, in main
    _main(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/pyprophet/main.py", line 345, in _main
    PyProphetLearner(pathes, prefix, merge_results, delim_in, delim_out).run()
  File "/usr/local/lib/python2.7/dist-packages/pyprophet/main.py", line 132, in run
    (result, scorer, weights) = self.run_algo()
  File "/usr/local/lib/python2.7/dist-packages/pyprophet/main.py", line 236, in run_algo
    self.check_cols)
  File "/usr/local/lib/python2.7/dist-packages/pyprophet/pyprophet.py", line 500, in learn_and_apply
    result, scorer, trained_weights = self._learn_and_apply(tables)
  File "/usr/local/lib/python2.7/dist-packages/pyprophet/pyprophet.py", line 511, in _learn_and_apply
    all_test_target_scores, all_test_decoy_scores)
  File "/usr/local/lib/python2.7/dist-packages/pyprophet/pyprophet.py", line 574, in _build_result
    final_statistics, summary_statistics = scorer.get_error_stats()
  File "/usr/local/lib/python2.7/dist-packages/pyprophet/pyprophet.py", line 189, in get_error_stats
    return final_err_table(self.error_stat.df), summary_err_table(self.error_stat.df)
  File "/usr/local/lib/python2.7/dist-packages/pyprophet/stats.py", line 302, in final_err_table
    sampled_cutoffs = np.linspace(min_ - margin, max_ + margin, num_cut_offs, dtype=np.float32)
TypeError: linspace() got an unexpected keyword argument 'dtype'
```

**Comment by uweschmitt** [comment]
you have to update numpy, look at pyprophet/setup.py
